apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmaps
  namespace: xpream
data:
  get_320_jobcard.conf: |
    input {
      jdbc {
        jdbc_driver_library => "/usr/share/logstash/mssql-jdbc-10.2.1.jre8.jar"
        jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"
        jdbc_connection_string => "jdbc:sqlserver://172.16.40.239:1433;databasename=db_xpream;encrypt=true;trustServerCertificate=true"
        jdbc_user => "usr-xpream"
        jdbc_password => "p@ssw0rd"
        sql_log_level => "debug"  # Set Logstash logging level as this
        clean_run => true # Set to true for indexing from scratch
        record_last_run => false
        statement_filepath => "/usr/share/logstash/config/queries/get_xpreamview_jc.sql"
        #schedule => "2 3 * * *"
      }
    }

    filter {
      #if [action_type] == "create" or [action_type] == "update" {
      #  mutate { add_field => { "[@metadata][action]" => "index" } }
      #} else if [action_type] == "delete" {
      #  mutate { add_field => { "[@metadata][action]" => "delete" } }
      #}

      mutate {
        remove_field => ["@version", "@timestamp", "action_type"]
        convert => {
            "pmhrs" => "float"
            "actmhrs" => "float"
        }
      }
    }

    output {
      stdout { codec => rubydebug { metadata => true } }
      elasticsearch {
        hosts => ["http://elastic-trb-database.xpream.svc.cluster.local:9200"]
        index => "job_card_airbus_320"
        #action => "%{[@metadata][action]}"
        action => "index"
        document_id => "%{id}"
      }
    }
  get_xpreamview_jc.sql: |
    SELECT XPREAM_JOBALLTRACKING_VIEW.* FROM
    db_xpream.dbo.XPREAM_JOBALLTRACKING_VIEW WHERE
    db_xpream.dbo.XPREAM_JOBALLTRACKING_VIEW.ac_type LIKE '%320%'
  logstash.yml: |
    http.host: "0.0.0.0"

    xpack.monitoring.enabled: true

    xpack.monitoring.elasticsearch.hosts: [
    "http://elastic-trb-database.xpream.svc.cluster.local:9200" ]

    log.level: info
  pipelines.yml: |
    - pipeline.id: getdbaccess-pipeline
      path.config: "/usr/share/logstash/pipeline/get_320_jobcard.conf"