apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-trb-database
  labels:
    service: elastic-trb-database
spec:
  serviceAccountName: xpreamadmin
  serviceName: elastic-trb-database
  replicas: 3
  selector:
    matchLabels:
      service: elastic-trb-database
  template:
    metadata:
      labels:
        service: elastic-trb-database
    spec:
      terminationGracePeriodSeconds: 300
      
      #################################################################################
      ##
      ##  XOPS INIT CONTAINER SECTION
      ##
      #################################################################################
      initContainers:
      - name: elasticsearch-init
        image: docker-registry.default.svc:5000/xpream/busybox:latest
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
        args:
          - sysctl -w vm.max_map_count=262144;
            ulimit -n 65536;
        securityContext:
          privileged: true

      - name: elasticsearch-init-permission
        image: docker-registry.default.svc:5000/xpream/busybox:latest
        command: ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
        securityContext:
          privileged: true
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data

      #################################################################################
      ##
      ##  XOPS MAIN CONTAINER SECTION
      ##
      #################################################################################     
      containers:
      - name: elasticsearch
        image: docker-registry.default.svc:5000/xpream/elasticsearch:8.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: tcp
        resources:
          requests:
            memory: 2Gi
          limits:
            memory: 4Gi
        env:
          - name: CLUSTER_NAME
            value: elastic-trb-database
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ES_JAVA_OPTS
            value: '-Xms512m -Xmx512m'
          - name: ELASTIC_PASSWORD
            value: xpr34mtrbd4t4b4s3
          - name: xpack.security.enabled
            value: 'false'
          - name: xpack.security.enrollment.enabled
            value: 'true'
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        - name: elasticsearch-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml

      #################################################################################
      ##
      ##  XOPS VOLUMES SECTION
      ##
      #################################################################################
      volumes:
      - name: elasticsearch-data
        persistentVolumeClaim:
          claimName: elasticsearch-data
      - name: elasticsearch-config  
        configMap:
          name: elastic-configmaps
          defaultMode: 0555
          items:
          - key: elasticsearch.yml
            path: elasticsearch.yml
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: glusterfs-storage-block
      resources:
        requests:
          storage: 3Gi